import SearchBar from '@/components/SearchBar';
import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import NavBar from '@/components/NavBar';
import usePages from '@/hooks/usePages';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col items-center">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
